from .bookmark_category_bulk_create_view import BookmarkCategoryBulkCreateAPIView
from .bookmark_category_bulk_delete_view import BookmarkCategoryBulkDeleteAPIView
from .bookmark_category_list_view import BookmarkCategoryListAPIView
from .bookmark_category_bulk_update_view import BookmarkCategoryBulkUpdateAPIView
from .bookmark_category_detail_view import BookmarkCategoryDetailAPIView
from .bookmark_bulk_create_view import BookmarkBulkCreateAPIView